
[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python3 -m pip install --upgrade pip
wandb: Using wandb-core as the SDK backend. Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: takonoselidze (takonoselidze-charles-university). Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.18.3
wandb: Run data is saved locally in /scratch.ssd/takonoselidze/job_6574058.pbs-m1.metacentrum.cz/wandb/run-20241117_225714-wxkqzpwt
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run upbeat-meadow-26
wandb: ‚≠êÔ∏è View project at https://wandb.ai/takonoselidze-charles-university/Random%20Position%20Patch_tmp_
wandb: üöÄ View run at https://wandb.ai/takonoselidze-charles-university/Random%20Position%20Patch_tmp_/runs/wxkqzpwt
Traceback (most recent call last):
  File "main.py", line 431, in <module>
    epoch_patches, target_classes = start(device, generator, optimizer, deployer, discriminators, dataloader, classes, num_of_epochs, brightness_factor, color_transfer)
  File "main.py", line 116, in start
    correct_counts += (predicted == target_class).float()
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
